---
version: '3'

services:
  notebook:
    container_name: notebook
    build:
      context: .
    image: dceoy/jupyter:latest
    ports:
      - 8888:8888
    volumes:
      - ${PWD}:/wd
    working_dir: /wd
