version: '3'

services:
  jupyter:
    container_name: jupyter
    build:
      context: .
    image: dceoy/jupyter:latest
    ports:
      - 8888:8888
    volumes:
      - ${PWD}:/work
    working_dir: /work
