---
version: '3'

services:
  notebook:
    container_name: notebook
    build:
      context: latest
    image: dceoy/jupyter:latest
    ports:
      - 8888:8888
    volumes:
      - ${PWD}:/wd
    working_dir: /wd
  nbconvert:
    container_name: nbconvert
    image: dceoy/pydata:latest
    user: ${UID}:${GID}
    volumes:
      - ${PWD}:/wd
    working_dir: /wd
    entrypoint:
      - jupyter
    command:
      - nbconvert
      - --to=notebook
      - --ExecutePreprocessor.timeout=-1
      - --execute
      - --inplace
      - --ExecutePreprocessor.kernel_name=python
